/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.18.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as cards from "../cards";
import type * as dealCards from "../dealCards";
import type * as games from "../games";
import type * as lib_functions from "../lib/functions";
import type * as lib_middlewareUtils from "../lib/middlewareUtils";
import type * as message from "../message";
import type * as model_cards from "../model/cards";
import type * as model_game from "../model/game";
import type * as model_message from "../model/message";
import type * as model_player from "../model/player";
import type * as model_user from "../model/user";
import type * as players from "../players";
import type * as prosetHelpers from "../prosetHelpers";
import type * as queries_getOngoingGames from "../queries/getOngoingGames";
import type * as revealProset from "../revealProset";
import type * as types_game_info from "../types/game_info";
import type * as types_player_colors from "../types/player_colors";
import type * as users from "../users";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  cards: typeof cards;
  dealCards: typeof dealCards;
  games: typeof games;
  "lib/functions": typeof lib_functions;
  "lib/middlewareUtils": typeof lib_middlewareUtils;
  message: typeof message;
  "model/cards": typeof model_cards;
  "model/game": typeof model_game;
  "model/message": typeof model_message;
  "model/player": typeof model_player;
  "model/user": typeof model_user;
  players: typeof players;
  prosetHelpers: typeof prosetHelpers;
  "queries/getOngoingGames": typeof queries_getOngoingGames;
  revealProset: typeof revealProset;
  "types/game_info": typeof types_game_info;
  "types/player_colors": typeof types_player_colors;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
