/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as claimSet from "../claimSet";
import type * as dealCards from "../dealCards";
import type * as discardRevealedProset from "../discardRevealedProset";
import type * as endGame from "../endGame";
import type * as getGameInfo from "../getGameInfo";
import type * as getPlayer from "../getPlayer";
import type * as getRecentMessages from "../getRecentMessages";
import type * as joinGame from "../joinGame";
import type * as maybeClearSelectSet from "../maybeClearSelectSet";
import type * as prosetHelpers from "../prosetHelpers";
import type * as queries_getMyGames from "../queries/getMyGames";
import type * as queries_getOngoingGames from "../queries/getOngoingGames";
import type * as revealProset from "../revealProset";
import type * as selectCard from "../selectCard";
import type * as sendMessage from "../sendMessage";
import type * as startGame from "../startGame";
import type * as startSelectSet from "../startSelectSet";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  claimSet: typeof claimSet;
  dealCards: typeof dealCards;
  discardRevealedProset: typeof discardRevealedProset;
  endGame: typeof endGame;
  getGameInfo: typeof getGameInfo;
  getPlayer: typeof getPlayer;
  getRecentMessages: typeof getRecentMessages;
  joinGame: typeof joinGame;
  maybeClearSelectSet: typeof maybeClearSelectSet;
  prosetHelpers: typeof prosetHelpers;
  "queries/getMyGames": typeof queries_getMyGames;
  "queries/getOngoingGames": typeof queries_getOngoingGames;
  revealProset: typeof revealProset;
  selectCard: typeof selectCard;
  sendMessage: typeof sendMessage;
  startGame: typeof startGame;
  startSelectSet: typeof startSelectSet;
}>;
